### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by razor9999** [CBiX/gotubecast#10]
root@raspberrypi:/home/pi/gotubecast/examples# ./raspi.sh 
Your pairing code: 538-391-572-221
SAMSUNG SM-G610F connected
panic: interface conversion: interface {} is nil, not string

goroutine 1 [running]:
main.genericCmd(0x7, 0x0, 0x11a18890, 0xb, 0x11ae2128, 0x1, 0x1)
	/root/gotubecast/main.go:291 +0x40a0
main.decodeBindStream(0x741afc18, 0x11b34210, 0x11b34210, 0x741afc18)
	/root/gotubecast/main.go:233 +0x104
main.main()
	/root/gotubecast/main.go:191 +0x11d4

**Comment by cbix** [comment]
Could you add `-d 1` to the gotubecast call in raspi.sh and post the output again? Thanks :)

**Comment by 70mmy** [comment]
The issue is at line 291:

`currentTime := data["currentTime"].(string)`

When setting the playlist there is no currentTime
